### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by jl109** [xinyadu/doc_event_entity#1]
Traceback (most recent call last):
  File "run_pl_s_t.py", line 424, in <module>
    model = NERTransformer.load_from_checkpoint(checkpoints[-1])
IndexError: list index out of range
请问这个错误怎么解决呢，

**Comment by jl109** [comment]
I have solved this problem and I am very interested in your paper. May I ask if it is feasible for me to change the data set to Chinese data set?Can you give me a good suggestion?

**Comment by jl109** [comment]
Thank you for your contribution and your code. I am trying to modify your code to train Chinese data. Unfortunately, my Chinese data format is the same as yours, but json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 583 (char 582)
 is the problem, may I ask why? In addition, I modified the Bert model you used in it, using BERT_BASE_CHINESE, and ROLE_LIST = ["BEG", "ORG", "NAME", "NUM", "END"]. Could you please tell me what else to modify? I hope you can guide me.As a graduate student, I am very interested in event extraction

**Comment by 18610752432** [comment]
> Traceback (most recent call last):
> File "run_pl_s_t.py", line 424, in
> model = NERTransformer.load_from_checkpoint(checkpoints[-1])
> IndexError: list index out of range
> 请问这个错误怎么解决呢，

想请教一下您这个问题是如何解决的？
